### ISSUE TITLE
kiedy release

### ISSUE THREAD

**Issue by inzynierr** [stevimeister/combat-plugin#1]
bo nie wiem

**Comment by stevimeister** [comment]
Nie wiem!

**Comment by marszello** [comment]
jutro chyba

**Comment by inzynierr** [comment]
no nadal czekam

**Comment by iuczony** [comment]
![image](https://user-images.githubusercontent.com/43303963/104933600-67c15280-59a9-11eb-92c0-9654673661d3.png)

**Comment by inzynierr** [comment]
![image](https://user-images.githubusercontent.com/45458831/105188100-d3372b80-5b33-11eb-8994-2de7dc51da49.png)

**Comment by stevimeister** [comment]
![clownshield](https://user-images.githubusercontent.com/39224663/105189591-09bd7800-5b2d-11eb-93ea-d3e2b8ddbc56.png)

**Comment by neightyy** [comment]
nieźle
